### ISSUE TITLE
Exception on program exit

### ISSUE THREAD

**Issue by vonengel** [vrsys/avango#7]
When existng an avango application by closing the window, I get the following exception:

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
/home/ddangelo/scripts/av_gua: line 20:  2911 Aborted                 (core dumped) python $*

**Comment by bernstein** [comment]
Finally fixed in guacamole with commit ebc4c9f65eea787ed935638c4f03e891e7949c66 .
