### ISSUE TITLE
assimp-3.1.1/code/Importer.cpp:738: const aiScene* Assimp::Importer::ApplyPostProcessing(unsigned int): Assertion `_ValidateFlags(pFlags)' failed.

### ISSUE THREAD

**Issue by ql-xxxiii** [vrsys/avango#98]
simple_example

scm <output> schism (0.7.9_x64_devel_release) 'metal, it comes from hell'
scm <output> startup time: 2017-Jul-10 14:39:00.033614000
scm <info> initializing scm.core:
scm <info>      - running pre core init functions
scm <info>      - parsing command line options
scm <info>      - running post core init functions
scm <info> successfully initialized scm.core:
scm <output> logging_core registered loggers:
              - 'scm.gl_core' with ptr instances: 1
              - 'scm' with ptr instances: 2
              - '' with ptr instances: 2

python: /builddir/build/BUILD/assimp-3.1.1/code/Importer.cpp:738: const aiScene* Assimp::Importer::ApplyPostProcessing(unsigned int): Assertion `_ValidateFlags(pFlags)' failed.
./start.sh: line 36:  4826 Aborted                 (core dumped) ./main.py

**Comment by bernstein** [comment]
dear everton, thanks for reporting the issue. i pushed an update to guacamole. please pull the latest changes and rebuild guacamole.
